http:
  host: localhost
  port: 9000
  maxHeaderMegabytes: 1
  readTimeout: 5s
  writeTimeout: 10s

auth:
  accessTokenTtl: 1h
  refreshTokenTtl: 48h
  sessionMax: 3

mongo:
  host: localhost
  port: 27017
  dbname: idler

cache:
  size: 100000
  expires: 4h