http:
  host: localhost
  port: 9000
  maxHeaderMegabytes: 1
  readTimeout: 5s
  writeTimeout: 10s

auth:
  tokenTTL: 180m

mongo:
  host: localhost
  port: 27017
  dbname: idler

cache:
  size: 100000
  expires: 4h